services:
  php:
    build:
      context: docker/php
      args:
        PHP_IMAGE: $PHP_IMAGE
    container_name: "${COMPOSE_PROJECT_NAME}-php"
    restart: always
    environment:
      HISTFILE: /root/history/.history
      ENV: /root/.bashrc
    volumes:
      - .:/var/www/html:cached
      - php_socket:/var/run/php
      - php_history:/root/history

  nginx:
    image: nginx:1.24-alpine3.17
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    restart: always
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/var/www/html/public:ro
      - php_socket:/var/run/php
    ports:
      - '${APP_PORT}:80'

  database:
    build:
      context: "./docker/mysql${MYSQL_VERSION}"
    container_name: "${COMPOSE_PROJECT_NAME}-database"
    restart: "always"
    volumes:
      - ${MYSQL_INITDB_DIR-./config/initdb}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  php_history: ~
  php_socket: ~
